# k8s/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: u-value-calculator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: u-value-calculator
  template:
    metadata:
      labels:
        app: u-value-calculator
    spec:
      containers:
      - name: u-value-calculator
        image: soumyatata/u-value-calculator:latest
        ports:
        - containerPort: 80
